jvm_binary(name = 'very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_name',
      dependencies = ["java_hellos_lib"],
      sources = ['com/**/*.java'],
      main = 'com.HelloWorld',
      basename = 'hello-example',
) 
